git commit --allow-empty -m "significant commit1"
git commit --allow-empty -m "fix typo"
git commit --allow-empty -m "add comments"
git commit --allow-empty -m "run pipeline"
git commit --allow-empty -m "add whitespace"
git commit --allow-empty -m "significant commit2"
git commit --allow-empty -m "run linter"
git commit --allow-empty -m "trying to rearrange stuff"
git commit --allow-empty -m "significant commit3"
git commit --allow-empty -m "run pipeline"
git commit --allow-empty -m "significant commit4"