name: backend-env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - flask
  - flask-cors
  - pymongo
  - werkzeug
  - pytest
  - pytest-cov
  - black
  - pip:
      - pymongo
      - pre-commit
      - bs4
      - keybert
