# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm install
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Compilation
        run: npm run build --if-present

      - name: Run Tests
        run: npm test -- --coverage

      - name: Code Coverage
        uses: codecov/codecov-action@v1.1.1
        with:
          # User defined upload name. Visible in Codecov UI
          name: verwiki-ui-tests
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}
          # Directory to search for coverage reports.
          directory: ./coverage
          # Specify whether the Codecov output should be verbose
          verbose: true
