# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Backend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8]
    
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Anaconda Env
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge

      - name: Activate Virtual Environment
        run: |
          conda env create -f backend/environment.yaml
          conda activate backend-env

      - name: Lint with Black
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: backend

      - name: Test with pytest
        run: |
          echo Testing Backend Scripts...
          pytest --cov-fail-under=90 --cov-report term-missing --cov=./backend backend

        # Needed
        # - Checking for code duplication
        # - Figure out a way to exclude repopulate_db.py from the coverage, since that is a testing file anyway
