# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Backend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    
    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Anaconda Env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: backend-env
          environment-file: backend/environment.yaml
          python-version: ${{ matrix.python-version }}

      - name: Lint with Black
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: backend

      - name: Test with pytest
        run: |
          conda activate backend-env
          pytest --cov-fail-under=90 --cov-report term-missing --cov=./backend backend

        # Needed
        # - Checking for code duplication
        # - Figure out a way to exclude repopulate_db.py from the coverage, since that is a testing file anyway
