# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Backend CI

# Allows the pipeline to run on all pushes and PRs
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          environment-file: backend/environment.yaml
          add-pip-as-python-dependency: true
          activate-environment: backend-env

      - name: Activate Virtual Env
        run: |
          conda activate backend-env
          echo $CONDA_DEFAULT_ENV

      - name: Lint with Black
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: backend

      - name: Duplicate Code Detection
        run: |
          git clone https://github.com/VerWiki/duplicate-code-detection-tool.git
          pip install nltk gensim
          python -m nltk.downloader punkt 
          python3 -W ignore duplicate-code-detection-tool/duplicate_code_detection.py -d backend -t 20 -i tests

      - name: Testing Backend
        run: |
          export PYTHONPATH=$PYTHONPATH:`pwd`/backend
          pytest --cov-fail-under=95 --cov-report term-missing --cov=./backend backend > backend-coverage.txt

      - name: Coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: backend-coverage.txt
