# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Backend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          environment-file: backend/environment.yaml
          add-pip-as-python-dependency: true
          activate-environment: backend-env

      - name: Install dependencies
        run: |
          conda activate backend-env
          echo $CONDA_DEFAULT_ENV
          which conda
          which pip
          conda list

      - name: Lint with Black
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: backend

      - name: Testing Backend
        run: |
          pytest --cov-fail-under=90 --cov-report term-missing --cov=./backend backend > backend-coverage.txt

      - name: Coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: backend-coverage.txt

        # Needed
        # - Checking for code duplication
        # - Figure out a way to exclude repopulate_db.py from the coverage, since that is a testing file anyway
